/* tslint:disable */


/**
 * AUTO-GENERATED FILE @ 2018-08-02 10:29:52 - DO NOT EDIT!
 *
 * This file was automatically generated by schemats v.3.0.3
 * $ schemats generate -c postgres://username:password@localhost/tourdb -t reviews -t users -t tours -s public
 *
 */


export namespace usersFields {
    export type id = string;
    export type email = string;
    export type family_name = string | null;
    export type given_name = string | null;

}

export interface users {
    id: usersFields.id;
    email: usersFields.email;
    family_name: usersFields.family_name;
    given_name: usersFields.given_name;

}
